plugins {
    id 'com.android.library'
}

def aneConfig = rootProject.ext.aneConfig

android {
    namespace 'com.ane.filemanager.plugin.api'
    compileSdk aneConfig.compileSdk

    defaultConfig {
        minSdk aneConfig.minSdk
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility aneConfig.javaVersion
        targetCompatibility aneConfig.javaVersion
    }
}
